server:
  port: 8022

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8001/eureka/,http://eureka01:8002/eureka/,http://eureka0:8003/eureka/
  instance:
    instance-id:  AUTH-CUSTOMER-HYSTRIX # 自定义展示名称
    prefer-ip-address: true # 浮动是否展示ip
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: AUTH-CUSTOMER-HYSTRIX # eureka上显示的服务名称标识
  datasource:
    server:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/auth_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root1234
      min-idle: 5 # the min survive counts connections in the pool
      initial-size: 5 # init the amount of connections
      max-total: 5 # max counts of connections
      max-wait-millis: 200 # max time to get a connection

# 配置feign的日志
feign:
  #开启对hystrix的支持
  hystrix:
    enabled: true
  #日志展示级别，方便排查问题
  client:
    config:
      auth-service:
        loggerLevel: FULL

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #默认的连接超时时间1秒,若1秒没有返回数据,自动的触发降级逻辑
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5
        errorThresholdPercentage: 10
        sleepWindowInMilliseconds: 10000