server:
  port: 3344

spring:
  application:
    name: cloud-user-config-demo
  cloud:
    config:
      server:
        git:
          uri: git@github.com:licunzhi/SpringCloudConfig.git #GitHub上面的git仓库名字
