server:
  port: 3344

spring:
  application:
    name: cloud-user-config-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/licunzhi/SpringCloudConfig.git #GitHub上面的git仓库名字
          username:
          password:
