server:
  port: 8088 #server running port

spring:
  application:
    name: cloud-user-service-demo-8088
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    dbcp2:
      min-idle: 5 # the min survive counts connections in the pool
      initial-size: 5 # init the amount of connections
      max-total: 5 # max counts of connections
      max-wait-millis: 200 # max time to get a connection

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.sakura.rain.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/,http://eureka8003.com:8003/eureka/
  instance:
    instance-id: cloud-user-demo-8088 # 自定义展示名称
    prefer-ip-address: true # 浮动是否展示ip

info:
  app.name: sakura-cloud-user-demo
  company.name: www.sakura.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
