server:
  port: 8020

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8001/eureka/,http://eureka01:8002/eureka/,http://eureka0:8003/eureka/
  instance:
    instance-id:  AUTH-CUSTOMER-FEIGN # 自定义展示名称
    prefer-ip-address: true # 浮动是否展示ip
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: AUTH-CUSTOMER-FEIGN # eureka上显示的服务名称标识
  datasource:
    server:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/auth_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root1234
      min-idle: 5 # the min survive counts connections in the pool
      initial-size: 5 # init the amount of connections
      max-total: 5 # max counts of connections
      max-wait-millis: 200 # max time to get a connection

#ribbon:
#  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#  OkToRetryOnAllOperations: true #对超时请求启用重试机制
#  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#  MaxAutoRetries: 1 # 切换实例后重试最大次数
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法